### ISSUE TITLE
[Bug]: Can't use generic helpers with `TypedContainer` in `strongly-typed`

### ISSUE THREAD

**Issue by alecgibson** [inversify/monorepo#170]
### Version

1.2.1

### Steps to reproduce

At the moment, you can't use the `TypedContainer` with a generic helper function:

```ts
      describe('generics', () => {
        it('can be used in a generic function', () => {
          function test<T extends BindingMap>(
            container: TypedContainer<T>,
          ): void {
            container.get('foo'); // error :(
          }

          test(container);
        });
      });
```

### Expected behavior

Would expect the above test to compile

### Actual behavior

Compilation error:

```
Argument of type 'string' is not assignable to parameter of type 'IfAny<IfAny<T, any, { [K in keyof T as T[K] extends Promise<any> ? never : K]: T[K]; }>, ServiceIdentifier<unknown>, keyof IfAny<T, any, { [K in keyof T as T[K] extends Promise<...> ? never : K]: T[K]; }>>'.ts(2345)
```

### Additional context

I think this may have something to do with the [`Synchronous`](https://github.com/inversify/monorepo/blob/74e939d7ab9d34d57836a6d626d212ceed9f819a/packages/container/libraries/strongly-typed/src/container.ts#L26) type definition.

If I remove this from the `get()` signature, then the above test compiles, but then obviously the test for not being able to `get()` a `Promise` fails compilation.

```diff
  get: <
-   TBound extends ContainerBinding<Synchronous<T>, TKey>,
-   TKey extends MappedServiceIdentifier<Synchronous<T>> = any,
+   TBound extends ContainerBinding<T, TKey>,
+   TKey extends MappedServiceIdentifier<T> = any,
  >(
    serviceIdentifier: TKey,
  ) => TBound;
```

### Environment

```Shell
System:
    OS: macOS 15.1.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 65.47 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.22 - ~/.yarn/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 8.12.1 - /opt/homebrew/bin/pnpm
    bun: 1.0.15 - ~/.bun/bin/bun
  npmPackages:
    @changesets/cli: 2.27.10 => 2.27.10 
    @commitlint/cli: 19.6.0 => 19.6.0 
    @commitlint/config-conventional: 19.6.0 => 19.6.0 
    @commitlint/prompt-cli: 19.6.0 => 19.6.0 
    @inversifyjs/foundation-eslint-config: workspace:* => undefined 
    @inversifyjs/foundation-jest-config: workspace:* => undefined 
    @inversifyjs/foundation-prettier-config: workspace:* => undefined 
    @inversifyjs/foundation-rollup-config: workspace:* => undefined 
    @inversifyjs/foundation-scripts: workspace:* => undefined 
    @inversifyjs/foundation-stryker-config: workspace:* => undefined 
    @inversifyjs/foundation-typescript-config: workspace:* => undefined 
    husky: 9.1.7 => 9.1.7 
    lint-staged: 15.2.10 => 15.2.10 
    turbo: 2.3.3 => 2.3.3
```

**Comment by notaphplover** [comment]
I see, I was thinking about the other approach I suggested regarding binding maps:

A binding map might be defined as a mapping of a non promise type:

```ts
interface MyBindingMap {
  foo: string;
}

const typedContainer = new TypedContainer<MyBindingMap>;

const fooService: string = typedContainer.get('foo');
const fooAsyncService: Promise<string> = typedContainer.getAsync('foo');
```

This way types would be simpler and they would probably work in the generic scenario we're dealing with in this issue.

How does it sound?

**Comment by alecgibson** [comment]
I'm not sure I'm a huge fan of that given that it works quite nicely now in hinting that something can *only* be accessed with `getAsync()`. I kind of think anything that gives you a compiler error to stop a runtime error is a good thing.

**Comment by alecgibson** [comment]
That being said, I think this issue probably arises because we're using a mapped type (`Synchronous`), which doesn't play nicely with generics. This is expected behaviour: https://github.com/microsoft/TypeScript/issues/35647

I guess a trivial example of where this code would never(?) work:

```ts
type BindingMap = {
  foo: any;
}

type OtherBindingMap = {
  foo: Promise<any>;
}

function doSomething<T extends BindingMap>(map: Synchronous<T>) {
  // here, `OtherBindingMap` fulfils the constraint `extends BindingMap`, but
  // we can clearly see that `Synchronous<OtherBindingMap>` is `{}`,
  // whereas `Synchronous<BindingMap>` is `BindingMap`, so I guess we can't
  // make any valid assumptions about the shape of `Synchronous<T>`

  map.foo // error
}
```

So I think we can *never* use `Synchronous` with any generic helpers...?

**Comment by alecgibson** [comment]
I wonder if the more pragmatic compromise solution is something like this:

```diff
  get: <
-   TBound extends ContainerBinding<Synchronous<T>, TKey>,
+   TBound extends ContainerBinding<T, TKey>,
-   TKey extends MappedServiceIdentifier<Synchronous<T>> = any,
+   TKey extends MappedServiceIdentifier<T> = any,
  >(
    serviceIdentifier: TKey,
- ) => TBound;
+ ) => TBound extends Promise<any> ? never : TBound;
```

With this we:

 - do away with the mapped type, so my generic helper test case now passes
 - no longer have a compiler error for `get('asyncBinding')` on its own, which is sad
 - ...but we *do* get a compiler error if you try to assign it (which you would anyway in like 99% of cases?), since its return type is resolved to `never`

What do you think @notaphplover ?

**Comment by notaphplover** [comment]
Hey @alecgibson :smiley: 

> What do you think @notaphplover ?

I see. Indeed an smart approach. I think it's the way to go given the exisitng language limitations. Feel free to submit a PR with your test case to cover the generic type case scenario and I'll have it a look :smiley:.
